### ISSUE TITLE
Writing awsBatchJobDetail files is too sensitive to EFS errors

### ISSUE THREAD

**Issue by sreeramsanjay** [miniwdl-ext/miniwdl-aws#21]
task are failing with below errors, noticed this issue especially when we ran 500+ concurrent tasks.

"message": "[Errno 2] No such file or directory: '/mnt/efs/miniwdl/20230422_204552_run_dl/call-run_dl_on_chrom/awsBatchJobDetail.df7b234543652-bcdwd-1234-ae80-75jkhs33f.json.tmp.b66a51f0-e153-11ed-b03d-ghj73gkjr93r' -> '/mnt/efs/miniwdl/20230422_204552_run_dl/call-run_dl_chrom/awsBatchJobDetail.df7b234543652-bcdwd-1234-ae80-75jkhs33f.json'".

**Comment by mlin** [comment]
Can you look at the EFS performance metrics (IOPS and throughput) to see if it may be getting overloaded? If so, there's some advice in the readme on [EFS performance considerations](https://github.com/miniwdl-ext/miniwdl-aws#efs-performance-considerations)

**Comment by mlin** [comment]
Hmmm, the only hack idea I have is if you're able to monkey-patch the miniwdl-aws code to comment out this call:

https://github.com/miniwdl-ext/miniwdl-aws/blob/243f36fdb44af1c59ce17844ec6641b0b2c3b837/miniwdl_aws/batch_job.py#L318-L321

It's just writing out the AWS Batch job details from the API (conceived when AWS Batch deleted this information after only 24h). That's causing some extra filesystem load/brittleness and isn't really necessary [now that AWS Batch retains that information](https://aws.amazon.com/about-aws/whats-new/2022/09/aws-batch-extends-job-report-retention-period-24-hours-7-days/) much longer. I will need to disable this or make an opt-in/out for it.

The `write_atomic` first writes out the content to a temp file, then renames it to the desired filename. My guess as to what may be happening is that the EFS is overloaded, not replying to all requests promptly, and the client retries the rename operation, but actually the first one did go through so the retry fails (since the source file was already renamed).

**Comment by sreeramsanjay** [comment]
Thank you, we will test this out. As of now we have enabled the maxRetries which seems to be working as well.

**Comment by mlin** [comment]
Published miniwdl-aws v0.10.0 including a patch (linked above) to write out the job details JSON file only when it's actually changed since the last time we wrote it. Although this doesn't totally eliminate the failure mode, it should reduce by orders of magnitude its opportunities to crash the job. There's more we can do, of course, if this doesn't suffice, but trying this relatively conservative change first.
